"""add rule based scoring

Revision ID: 0f666edeee8b
Revises: dbc05f836cff
Create Date: 2026-05-21 22:06:11.882633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f666edeee8b'
down_revision: Union[str, Sequence[str], None] = 'dbc05f836cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('dispatcher_user_id', sa.Integer(), nullable=False),
    sa.Column('rate_weight', sa.Float(), nullable=False),
    sa.Column('rpm_weight', sa.Float(), nullable=False),
    sa.Column('mileage_weight', sa.Float(), nullable=False),
    sa.Column('origin_weight', sa.Float(), nullable=False),
    sa.Column('destination_weight', sa.Float(), nullable=False),
    sa.Column('broker_weight', sa.Float(), nullable=False),
    sa.Column('driver_preference_weight', sa.Float(), nullable=False),
    sa.Column('preferred_origin_states', sa.JSON(), nullable=True),
    sa.Column('preferred_destination_states', sa.JSON(), nullable=True),
    sa.Column('preferred_brokers', sa.JSON(), nullable=True),
    sa.Column('avoided_brokers', sa.JSON(), nullable=True),
    sa.Column('max_miles', sa.Integer(), nullable=True),
    sa.Column('min_rate', sa.Float(), nullable=True),
    sa.Column('min_rate_per_mile', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['dispatcher_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'dispatcher_user_id', name='uq_scoring_preferences_company_dispatcher')
    )
    op.create_index(op.f('ix_scoring_preferences_company_id'), 'scoring_preferences', ['company_id'], unique=False)
    op.create_index(op.f('ix_scoring_preferences_dispatcher_user_id'), 'scoring_preferences', ['dispatcher_user_id'], unique=False)
    op.create_index(op.f('ix_scoring_preferences_id'), 'scoring_preferences', ['id'], unique=False)
    op.create_table('scoring_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('dispatcher_user_id', sa.Integer(), nullable=False),
    sa.Column('load_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.Column('truck_search_session_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['dispatcher_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.ForeignKeyConstraint(['load_snapshot_id'], ['load_snapshots.id'], ),
    sa.ForeignKeyConstraint(['truck_search_session_id'], ['truck_search_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispatcher_user_id', 'load_snapshot_id', name='uq_scoring_results_dispatcher_snapshot')
    )
    op.create_index(op.f('ix_scoring_results_company_id'), 'scoring_results', ['company_id'], unique=False)
    op.create_index(op.f('ix_scoring_results_dispatcher_user_id'), 'scoring_results', ['dispatcher_user_id'], unique=False)
    op.create_index(op.f('ix_scoring_results_id'), 'scoring_results', ['id'], unique=False)
    op.create_index(op.f('ix_scoring_results_load_id'), 'scoring_results', ['load_id'], unique=False)
    op.create_index(op.f('ix_scoring_results_load_snapshot_id'), 'scoring_results', ['load_snapshot_id'], unique=False)
    op.create_index(op.f('ix_scoring_results_score'), 'scoring_results', ['score'], unique=False)
    op.create_index(op.f('ix_scoring_results_truck_search_session_id'), 'scoring_results', ['truck_search_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scoring_results_truck_search_session_id'), table_name='scoring_results')
    op.drop_index(op.f('ix_scoring_results_score'), table_name='scoring_results')
    op.drop_index(op.f('ix_scoring_results_load_snapshot_id'), table_name='scoring_results')
    op.drop_index(op.f('ix_scoring_results_load_id'), table_name='scoring_results')
    op.drop_index(op.f('ix_scoring_results_id'), table_name='scoring_results')
    op.drop_index(op.f('ix_scoring_results_dispatcher_user_id'), table_name='scoring_results')
    op.drop_index(op.f('ix_scoring_results_company_id'), table_name='scoring_results')
    op.drop_table('scoring_results')
    op.drop_index(op.f('ix_scoring_preferences_id'), table_name='scoring_preferences')
    op.drop_index(op.f('ix_scoring_preferences_dispatcher_user_id'), table_name='scoring_preferences')
    op.drop_index(op.f('ix_scoring_preferences_company_id'), table_name='scoring_preferences')
    op.drop_table('scoring_preferences')
    # ### end Alembic commands ###
