"""add dispatcher load actions

Revision ID: 2cd0249de0bf
Revises: ab52e736ca2b
Create Date: 2026-05-21 20:02:08.879049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd0249de0bf'
down_revision: Union[str, Sequence[str], None] = 'ab52e736ca2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatcher_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('truck_search_session_id', sa.Integer(), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.Column('load_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('dispatcher_user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['dispatcher_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.ForeignKeyConstraint(['load_snapshot_id'], ['load_snapshots.id'], ),
    sa.ForeignKeyConstraint(['truck_search_session_id'], ['truck_search_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatcher_actions_action_type'), 'dispatcher_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_dispatcher_actions_company_id'), 'dispatcher_actions', ['company_id'], unique=False)
    op.create_index(op.f('ix_dispatcher_actions_dispatcher_user_id'), 'dispatcher_actions', ['dispatcher_user_id'], unique=False)
    op.create_index(op.f('ix_dispatcher_actions_id'), 'dispatcher_actions', ['id'], unique=False)
    op.create_index(op.f('ix_dispatcher_actions_load_id'), 'dispatcher_actions', ['load_id'], unique=False)
    op.create_index(op.f('ix_dispatcher_actions_load_snapshot_id'), 'dispatcher_actions', ['load_snapshot_id'], unique=False)
    op.create_index(op.f('ix_dispatcher_actions_truck_search_session_id'), 'dispatcher_actions', ['truck_search_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispatcher_actions_truck_search_session_id'), table_name='dispatcher_actions')
    op.drop_index(op.f('ix_dispatcher_actions_load_snapshot_id'), table_name='dispatcher_actions')
    op.drop_index(op.f('ix_dispatcher_actions_load_id'), table_name='dispatcher_actions')
    op.drop_index(op.f('ix_dispatcher_actions_id'), table_name='dispatcher_actions')
    op.drop_index(op.f('ix_dispatcher_actions_dispatcher_user_id'), table_name='dispatcher_actions')
    op.drop_index(op.f('ix_dispatcher_actions_company_id'), table_name='dispatcher_actions')
    op.drop_index(op.f('ix_dispatcher_actions_action_type'), table_name='dispatcher_actions')
    op.drop_table('dispatcher_actions')
    # ### end Alembic commands ###
