"""add load board sessions table

Revision ID: 8b1d9daba23d
Revises: a62571473418
Create Date: 2026-05-21 14:04:26.983054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b1d9daba23d'
down_revision: Union[str, Sequence[str], None] = 'a62571473418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('load_board_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('board_name', sa.String(), nullable=False),
    sa.Column('session_label', sa.String(), nullable=True),
    sa.Column('username_or_email', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('health_status', sa.String(), nullable=False),
    sa.Column('health_message', sa.Text(), nullable=True),
    sa.Column('debug_notes', sa.Text(), nullable=True),
    sa.Column('last_health_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_load_board_sessions_company_id'), 'load_board_sessions', ['company_id'], unique=False)
    op.create_index(op.f('ix_load_board_sessions_id'), 'load_board_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_load_board_sessions_id'), table_name='load_board_sessions')
    op.drop_index(op.f('ix_load_board_sessions_company_id'), table_name='load_board_sessions')
    op.drop_table('load_board_sessions')
    # ### end Alembic commands ###
