"""add search batch session and worker log models

Revision ID: 9b6ca9f7c7a4
Revises: 8b1d9daba23d
Create Date: 2026-05-21 15:05:32.664715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b6ca9f7c7a4'
down_revision: Union[str, Sequence[str], None] = '8b1d9daba23d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('filters_snapshot', sa.JSON(), nullable=True),
    sa.Column('total_trucks', sa.Integer(), nullable=False),
    sa.Column('completed_trucks', sa.Integer(), nullable=False),
    sa.Column('failed_trucks', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_batches_company_id'), 'search_batches', ['company_id'], unique=False)
    op.create_index(op.f('ix_search_batches_created_by_user_id'), 'search_batches', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_search_batches_id'), 'search_batches', ['id'], unique=False)
    op.create_table('truck_search_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_batch_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('filters_snapshot', sa.JSON(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['search_batch_id'], ['search_batches.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_truck_search_sessions_company_id'), 'truck_search_sessions', ['company_id'], unique=False)
    op.create_index(op.f('ix_truck_search_sessions_id'), 'truck_search_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_truck_search_sessions_owner_user_id'), 'truck_search_sessions', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_truck_search_sessions_search_batch_id'), 'truck_search_sessions', ['search_batch_id'], unique=False)
    op.create_index(op.f('ix_truck_search_sessions_truck_id'), 'truck_search_sessions', ['truck_id'], unique=False)
    op.create_table('worker_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('truck_search_session_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['truck_search_session_id'], ['truck_search_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_logs_company_id'), 'worker_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_worker_logs_id'), 'worker_logs', ['id'], unique=False)
    op.create_index(op.f('ix_worker_logs_truck_search_session_id'), 'worker_logs', ['truck_search_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_logs_truck_search_session_id'), table_name='worker_logs')
    op.drop_index(op.f('ix_worker_logs_id'), table_name='worker_logs')
    op.drop_index(op.f('ix_worker_logs_company_id'), table_name='worker_logs')
    op.drop_table('worker_logs')
    op.drop_index(op.f('ix_truck_search_sessions_truck_id'), table_name='truck_search_sessions')
    op.drop_index(op.f('ix_truck_search_sessions_search_batch_id'), table_name='truck_search_sessions')
    op.drop_index(op.f('ix_truck_search_sessions_owner_user_id'), table_name='truck_search_sessions')
    op.drop_index(op.f('ix_truck_search_sessions_id'), table_name='truck_search_sessions')
    op.drop_index(op.f('ix_truck_search_sessions_company_id'), table_name='truck_search_sessions')
    op.drop_table('truck_search_sessions')
    op.drop_index(op.f('ix_search_batches_id'), table_name='search_batches')
    op.drop_index(op.f('ix_search_batches_created_by_user_id'), table_name='search_batches')
    op.drop_index(op.f('ix_search_batches_company_id'), table_name='search_batches')
    op.drop_table('search_batches')
    # ### end Alembic commands ###
