"""add trucks and drivers tables

Revision ID: a62571473418
Revises: 54822fd38e7a
Create Date: 2026-05-20 23:26:10.028259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a62571473418'
down_revision: Union[str, Sequence[str], None] = '54822fd38e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('home_location', sa.String(), nullable=True),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_company_id'), 'drivers', ['company_id'], unique=False)
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_table('trucks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.String(), nullable=False),
    sa.Column('current_driver_id', sa.Integer(), nullable=True),
    sa.Column('current_driver_name', sa.String(), nullable=True),
    sa.Column('current_driver_surname', sa.String(), nullable=True),
    sa.Column('equipment_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['current_driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trucks_company_id'), 'trucks', ['company_id'], unique=False)
    op.create_index(op.f('ix_trucks_current_driver_id'), 'trucks', ['current_driver_id'], unique=False)
    op.create_index(op.f('ix_trucks_id'), 'trucks', ['id'], unique=False)
    op.create_index(op.f('ix_trucks_truck_id'), 'trucks', ['truck_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trucks_truck_id'), table_name='trucks')
    op.drop_index(op.f('ix_trucks_id'), table_name='trucks')
    op.drop_index(op.f('ix_trucks_current_driver_id'), table_name='trucks')
    op.drop_index(op.f('ix_trucks_company_id'), table_name='trucks')
    op.drop_table('trucks')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_company_id'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
