"""add booked loads

Revision ID: dbc05f836cff
Revises: 2cd0249de0bf
Create Date: 2026-05-21 20:33:35.322986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc05f836cff'
down_revision: Union[str, Sequence[str], None] = '2cd0249de0bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booked_loads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.Column('load_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('truck_search_session_id', sa.Integer(), nullable=True),
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('dispatcher_user_id', sa.Integer(), nullable=False),
    sa.Column('broker_name', sa.String(), nullable=True),
    sa.Column('equipment_type', sa.String(), nullable=True),
    sa.Column('origin_city', sa.String(), nullable=True),
    sa.Column('origin_state', sa.String(), nullable=True),
    sa.Column('destination_city', sa.String(), nullable=True),
    sa.Column('destination_state', sa.String(), nullable=True),
    sa.Column('pickup_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_rate', sa.Float(), nullable=True),
    sa.Column('final_rate', sa.Float(), nullable=True),
    sa.Column('miles', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['dispatcher_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.ForeignKeyConstraint(['load_snapshot_id'], ['load_snapshots.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.ForeignKeyConstraint(['truck_search_session_id'], ['truck_search_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booked_loads_company_id'), 'booked_loads', ['company_id'], unique=False)
    op.create_index(op.f('ix_booked_loads_dispatcher_user_id'), 'booked_loads', ['dispatcher_user_id'], unique=False)
    op.create_index(op.f('ix_booked_loads_driver_id'), 'booked_loads', ['driver_id'], unique=False)
    op.create_index(op.f('ix_booked_loads_id'), 'booked_loads', ['id'], unique=False)
    op.create_index(op.f('ix_booked_loads_load_id'), 'booked_loads', ['load_id'], unique=False)
    op.create_index(op.f('ix_booked_loads_load_snapshot_id'), 'booked_loads', ['load_snapshot_id'], unique=False)
    op.create_index(op.f('ix_booked_loads_status'), 'booked_loads', ['status'], unique=False)
    op.create_index(op.f('ix_booked_loads_truck_id'), 'booked_loads', ['truck_id'], unique=False)
    op.create_index(op.f('ix_booked_loads_truck_search_session_id'), 'booked_loads', ['truck_search_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booked_loads_truck_search_session_id'), table_name='booked_loads')
    op.drop_index(op.f('ix_booked_loads_truck_id'), table_name='booked_loads')
    op.drop_index(op.f('ix_booked_loads_status'), table_name='booked_loads')
    op.drop_index(op.f('ix_booked_loads_load_snapshot_id'), table_name='booked_loads')
    op.drop_index(op.f('ix_booked_loads_load_id'), table_name='booked_loads')
    op.drop_index(op.f('ix_booked_loads_id'), table_name='booked_loads')
    op.drop_index(op.f('ix_booked_loads_driver_id'), table_name='booked_loads')
    op.drop_index(op.f('ix_booked_loads_dispatcher_user_id'), table_name='booked_loads')
    op.drop_index(op.f('ix_booked_loads_company_id'), table_name='booked_loads')
    op.drop_table('booked_loads')
    # ### end Alembic commands ###
